### PR TITLE
Linq Expression conversion & Refactoring

### PR DESCRIPTION
**Pull request by alexis-**
* Added **Expression\<Func\<T, bool\>\> ToLinqExpression\<T\>()** Method which converts a FilterScheme instance to a LINQ Expression.
* Added a simple test to compare ToLinqExpression with ComputeResult results. More tests should be added to make sure all operators are operational.
* Split project in platform-agnostic code (Conditions, Properties, etc.) and platform-specific (WPF in that case) code. This results in two Shared projects instead of one : **Orc.FilterBuilder.Shared** and **Orc.FilterBuilder.Shared.WPF**. Motivation behind this is allowing to extend filter queries to other platforms (such as Xamarin). There may be more work to be done in that regard, more specifically, concerning Reflection being left in the platform-agnostic shared project.
* Updated Catel dependencies to 4.5.3
* TODO: Add Regex and Enum (**StringExpression**) handling in **ToLinqExpression**

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Good day, thanks for the PR. It contains a lot of changes so we will need to review carefully. The ToLinqExpression is a really nice addition. I am not sure if we are ready to split assemblies up (yet). but it's something we can consider.

**Comment by GeertvanHorrik** [comment]
I see there is also another pull request. Does that one make this obsolete? To be honest I think it's easier to create separate pull requests for each feature (but I understand this is a bit hard afterwards). For example:

1. PR for ToLinqExpression
2. PR for splitting up projects
3. PR for updated ui, etc

**Comment by alexis-** [comment]
Hello Geert,

I believe I understand why it can be easier for you to integrate separate isolated features.
Apology about the confusion with the two PR, I tried to be as concise as possible.

The other PR comes with additional features, but also includes the changes isolated in the one we are currently commenting (Linq + split projects).
As it is more change intesive, I thought I'd make a separate Pull Request which would allow you to decide whether or not this is useful enough to be integrated, while retaining the possibility of integrating only the Linq feature.

I had not thought of making the project splitting a separate PR, although it clearly makes sense.

I am not yet familiar with PR best-practice so these are good tips I am keen on using from now on, thanks.

How should we proceed from here ?

**Comment by GeertvanHorrik** [comment]
Ideally I would love to see separate pull requests. We are about to finalize the stable versions of all Orc.* packages for a stable release and I could include the ToLinqExpression in there. The rest is in a too early stage to include.

Basically you should:

1. Backup your local repository (just in case)
2. Refork Orc.FilterBuilder
3. Create separate branches (pr/tolinqexpression, pr/stacking-ui, pr/projectseparation, etc). Then each PR branch can be a separate PR.

If you need help, let me know.

**Pull request closed without merging**
