### PR TITLE
Core-UI Separation of concerns

### PR DESCRIPTION
**Pull request by alexis-**
* Moved UI related items to their own Shared Project (WPF in this case) **Orc.FilterBuilder.Shared.WPF**

### CODE REVIEW

**Comment by alexis-** [comment]
This, of course, does not include New-UI PR.
Some files would need to be moved in the new UI shared project to work with New-UI

**Comment by GeertvanHorrik** [comment]
It's only a shared project, right? No separation of assemblies (yet)?

**Comment by alexis-** [comment]
Correct.

**Comment by GeertvanHorrik** [comment]
Looks good, thanks.

**Pull request merged**
