### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by alexis-**
- New UI and condition building system for filter builder. The idea is to make the interface as intuitive as possible. Whether this is achieved here is of course open to criticism.
- Renamed **FilterBuilderView[Model]** to **FilterManagerView[Model]**, I personnaly always got confused about its content.
- Added new **FilterBuilderView[Model]** which handles display and editing calls for building **FilterScheme**.
- Moved **EditFilterView[Model]** filter-building part to said new **FilterBuilderView[Model]** couple (well, triple .xaml[.cs])
- Added filter tree building logic to **FilterSchemeExtensions.cs**
- Added **StackTreeView.xaml** which defines the new styling items for TreeView filter rendering
- Added **FilterBuilderGrayBrush#** color brushes to **Generic.xaml** to style the TreeView colors

Sample

### CODE REVIEW

**Comment by alexis-** [comment]
In case you decide this is useful, and merge the new interface, you might be interested in knowing I will probably drag-drop support to move conditions and properties around.

**Comment by GeertvanHorrik** [comment]
Thanks for including the screenshot, that's much appreciated. Drag & drop would be awesome! Not sure about the large indentation yet, but I will ask a few existing users what they think of this.

**Comment by GeertvanHorrik** [comment]
I've discussed this with a few users. They would like drag & drop support. Here are a few comments:

image

**Comment by alexis-** [comment]
I can only agree with your observations.

I've put some more work into the new UI, here's the result :
New Features

* Drag-Drop
  * Moving
  * Copying
  * Works on groups and properties
* Tree optimization
  * Group properties together, before groups
  * Merge single properties inside a group with parent

**Comment by alexis-** [comment]
Re: shift key down issue,

It seem to only happen with numeric values :
`<TextBox Text="{Binding DataTypeExpression.Value}">
                        <TextBox.Visibility>
                            <Binding Path="DataTypeExpression.ValueControlType"
                                     Converter="{StaticResource ValueControlTypeVisibilityConverter}">
                                <Binding.ConverterParameter>
                                    <x:Array Type="{x:Type expressionsViewModels:ValueControlType}">
                                        <expressionsViewModels:ValueControlType>Byte</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>SByte</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>Short</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>UnsignedShort</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>Integer</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>UnsignedInteger</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>Long</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>UnsignedLong</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>Decimal</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>Float</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>Double</expressionsViewModels:ValueControlType>
                                        <expressionsViewModels:ValueControlType>Numeric</expressionsViewModels:ValueControlType>
                                    </x:Array>
                                </Binding.ConverterParameter>
                            </Binding>
                        </TextBox.Visibility>
                        <i:Interaction.Behaviors>
                            <catel:NumericTextBox IsDecimalAllowed="{Binding DataTypeExpression.IsDecimal}"
                                                  IsNegativeAllowed="{Binding DataTypeExpression.IsSigned}"
                                                  UpdateBindingOnTextChanged="False" />
                            <catel:UpdateBindingOnTextChanged UpdateDelay="500" />
                        </i:Interaction.Behaviors>
                    </TextBox>`

I've checked and this issue seem to also be present on your current version.
I will create an issue.

**Comment by GeertvanHorrik** [comment]
Thanks for the updates. Just ping me whenever you think it's ready. Make sure to also merge upstream/develop so the merge conflicts are solved (we already accepted your PR for the shared projects update).

**Comment by alexis-** [comment]
I see. I think the feature should be about ready.

I have already done the merging work in my own develop branch. I'm not sure I have time to do that work again right now. Do you believe you can work with a PR from my develop branch ?

**Comment by GeertvanHorrik** [comment]
At the moment we have merge conflicts and cannot merge this PR to anything. What you should do to solve this is:

1. Add upstream master / develop to your repository
2. "git pull upstream develop" on your develop branch
3. Merge develop into your PR branch

**Comment by alexis-** [comment]
Done, can you confirm this is correct ?

**Comment by GeertvanHorrik** [comment]
See this:

image

**Comment by GeertvanHorrik** [comment]
I also can't see any commits, but basically here is the process:

1. Add upstream (you only have to set up this once per repository):

```
git remote add upstream https://github.com/WildGums/Orc.FilterBuilder.git
```

2. Switch to develop (you want to sync remote develop with local develop, not with your feature branch)

3. Pull upstream develop (sync WildGums/Orc.FilterBuilder/develop with alexis-/Orc.FilterBuilder/develop)

```
git pull upstream develop
```

4. Switch back to your feature branch

5. Merge the develop branch into your feature branch

**Pull request closed without merging**
