### PR TITLE
Add DisplayAttribute detection to PropertyMetadata and some localization

### PR DESCRIPTION
**Pull request by sunnycase**
1. Add DisplayAttribute detection to PropertyMetadata 
2. Add DisplayAttribute-based localization to Condition/ConditionGroupType

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Thanks for this PR. Very nice that you are thinking of localization, we have it planned (but haven't found time yet). Inside Catel, we have the ILanguageService (which comes with the LanguageBinding markup extension). We prefer to use that one (it also uses resx files to read), but people that want to use a db instead can also use that (they just have to replace the service). Interested in giving that a spin?

**Comment by sunnycase** [comment]
But it seems Catel didn't provide an attribute to get localized text via ILanguageService from metadata(Like PropertyInfo, FiledInfo).Because when a FilterEditor shows a property's displayName, there isn't a way to use LanguageBinding, all information comes from the model's metadata. I think the pattern of System.ComponentModel.DataAnnotations.DisplayAttribute is very useful.

**Comment by GeertvanHorrik** [comment]
I think you are right. What if we change the provide a bit to reflect something like this:

```
if (propertyInfo != null)  
{  
    var dispAttr = (DisplayAttribute)Attribute.GetCustomAttribute(propertyInfo, typeof(DisplayAttribute));  
    if (dispAttr != null)  
    {
        // First try: prefer the language service
       var displayName = _languageService.GetString(dispAttr.Name);
       if (string.IsNullOrWhitespace(displayName ))
       {
             displayName = dispAttr.GetName();
       }
       
        return displayName;
    }
}
```

**Comment by GeertvanHorrik** [comment]
And we might provide a custom version of DisplayNameAttribute in Catel vNext that supports the LanguageService out of the box.

**Comment by sunnycase** [comment]
It's great.

发自我的 Windows Phone
________________________________
发件人: Geert van Horrik<mailto:notifications@github.com>
发送时间: ‎2015/‎10/‎19 19:10
收件人: WildGums/Orc.FilterBuilder<mailto:Orc.FilterBuilder@noreply.github.com>
抄送: sunnycase<mailto:sunnycase@live.cn>
主题: Re: [Orc.FilterBuilder] Add DisplayAttribute detection to PropertyMetadata and some localization (#9)

And we might provide a custom version of DisplayNameAttribute in Catel vNext that supports the LanguageService out of the box.

---

**Comment by GeertvanHorrik** [comment]
DisplayNameAttribute is fixed. Unfortunately ms decided to seal the DisplayAttribute :-(

**Comment by GeertvanHorrik** [comment]
Released a new version of Catel. If you upgrade to the latest prerelease, you should be able to use the LanguageService.

**Comment by sunnycase** [comment]
There's a problem that DisplayNameAttribute cannot be applied to a field(enum either) but DisplayAttribute can. So Condition/ConditionGroupType still cannot use LanguageService to localize.

**Comment by GeertvanHorrik** [comment]
You are right. I have customized the DisplayNameAttribute, not the DisplayAttribute. By default (even the .net implementation) cannot be used on fields.

Let me think how to solve that.

**Comment by GeertvanHorrik** [comment]
I think we are nearly forced to use converters, which is not the way I want to go...

**Comment by GeertvanHorrik** [comment]
Also adding a converter to Catel so we can easily use the DisplayNameAttribute in combination with a converter.

**Comment by GeertvanHorrik** [comment]
Released new version of Catel with converter.

**Comment by sunnycase** [comment]
I have updated the patch to use ObjectToDisplayNameConverter to localize Condition/ConditionGroupType.

**Comment by GeertvanHorrik** [comment]
Thank you very much for the update. Reviewing now. If this works we will definitely add more languages to Orc.FilterBuilder, so it's a really good PR.

**Comment by GeertvanHorrik** [comment]
I think it looks good :)

image

**Comment by GeertvanHorrik** [comment]
@sunnycase thank you very much, really appreciated.

**Pull request merged**
